"""Generate all fab_campaign Gerber / drill / SVG files for the probe-fed patch.

Run from the repo root:
    .venv/bin/python fab_campaign/generate_fab.py

Output (all under fab_campaign/gerber/):
    patch_top_copper.gbr     - patch rectangle only (no stub)
    patch_bottom_copper.gbr  - full ground plane with anti-pad void
    patch_edge_cuts.gbr      - board outline (Profile, NP)
    patch_top_soldermask.gbr - top solder mask opening (matches patch + drill keepout)
    patch_bot_soldermask.gbr - bottom solder mask opening (12 mm circle over anti-pad)
    patch.drl                - Excellon drill file: 1 x 1.6 mm NPTH at feed point
    patch_top_copper.svg     - SVG preview of top copper
    patch_bottom_copper.svg  - SVG preview of bottom copper
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

# Allow running from the repo root without install.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from shapely.geometry import MultiPolygon, Point, Polygon

from gradenna.fab import (
    check_min_gap,
    check_min_width,
    write_gerber,
    write_svg,
)

# ---------------------------------------------------------------------------
# Physical constants (mirrors benchmarks/openems_refs/geometry.py exactly)
# ---------------------------------------------------------------------------
C0 = 299_792_458.0
F0 = 2.45e9
EPS_FR4 = 4.3
H_SUB = 1.6e-3  # m

MARGIN_MM = 5.0  # board margin beyond patch on each side


def _patch_design(fr: float, eps_r: float, h: float) -> tuple[float, float, float]:
    """Balanis TL design -- identical to geometry.py and gradenna.designs."""
    w = C0 / (2.0 * fr) * math.sqrt(2.0 / (eps_r + 1.0))
    eps_reff = (eps_r + 1.0) / 2.0 + (eps_r - 1.0) / 2.0 * (1.0 + 12.0 * h / w) ** -0.5
    dl = (
        0.412
        * h
        * ((eps_reff + 0.3) * (w / h + 0.264))
        / ((eps_reff - 0.258) * (w / h + 0.8))
    )
    length = C0 / (2.0 * fr * math.sqrt(eps_reff)) - 2.0 * dl
    return w, length, eps_reff


# ---------------------------------------------------------------------------
# Derived dimensions (all in mm)
# ---------------------------------------------------------------------------
_w_m, _l_m, EPS_REFF = _patch_design(F0, EPS_FR4, H_SUB)
W_MM = _w_m * 1e3   # patch width  ~37.5839 mm
L_MM = _l_m * 1e3   # patch length ~29.1383 mm

BOARD_X = W_MM + 2 * MARGIN_MM  # ~47.5839 mm
BOARD_Y = L_MM + 2 * MARGIN_MM  # ~39.1383 mm

# Patch rectangle (margin offset from board origin)
PATCH_X0 = MARGIN_MM
PATCH_Y0 = MARGIN_MM
PATCH_X1 = MARGIN_MM + W_MM
PATCH_Y1 = MARGIN_MM + L_MM

# Feed point: W-centre, 1.2 mm inset from the near radiating edge (y = PATCH_Y0).
# This mirrors PatchGeometry.feed_offset_y() == 1.2e-3 m in geometry.py.
FEED_X = MARGIN_MM + W_MM / 2.0   # ~23.7919 mm
FEED_Y = PATCH_Y0 + 1.2           # ~6.2000 mm

# Drill: 1.6 mm diameter NPTH (SMA centre pin 1.27 mm + clearance)
DRILL_DIA = 1.6  # mm

# Anti-pad on bottom ground: clearance circle, 4.0 mm diameter
ANTIPAD_R = 2.0  # mm radius (4.0 mm diameter)

# Bottom solder-mask opening: 12.0 mm diameter circle over the anti-pad
# centre. The opening must expose enough ground copper around the 4 mm
# anti-pad void for the SMA flange body to be soldered to (a 5 mm opening
# would leave only a 0.5 mm annulus of exposed copper).
BOTMASK_R = 6.0  # mm radius


def _rect(x0: float, y0: float, x1: float, y1: float) -> Polygon:
    return Polygon([(x0, y0), (x1, y0), (x1, y1), (x0, y1)])


def _circle(cx: float, cy: float, r: float, n: int = 64) -> Polygon:
    angles = [2 * math.pi * i / n for i in range(n)]
    pts = [(cx + r * math.cos(a), cy + r * math.sin(a)) for a in angles]
    return Polygon(pts)


def _write_excellon(path: Path, holes: list[tuple[float, float, float]]) -> None:
    """Write a minimal JLCPCB-compatible Excellon drill file.

    Args:
        path: Output file path.
        holes: List of (x_mm, y_mm, diameter_mm) tuples.
    """
    # Group by tool diameter
    tools: dict[float, list[tuple[float, float]]] = {}
    for x, y, d in holes:
        tools.setdefault(d, []).append((x, y))

    lines = [
        "M48",
        "; DRILL file generated by gradenna fab_campaign/generate_fab.py",
        "; FORMAT={-:-/ absolute / metric / decimal}",
        "METRIC,TZ",  # trailing zeros suppressed; METRIC units
    ]
    tool_idx = {dia: f"T{i+1:02d}" for i, dia in enumerate(sorted(tools))}
    for dia, code in sorted(tool_idx.items(), key=lambda kv: kv[1]):
        lines.append(f"{code}C{dia:.3f}")
    lines.append("%")  # end of header
    lines.append("G90")  # absolute mode
    lines.append("G05")  # drill mode

    for dia, code in sorted(tool_idx.items(), key=lambda kv: kv[1]):
        lines.append(code)
        for x, y in tools[dia]:
            # Excellon METRIC,TZ: coordinates in 0.001 mm resolution (3 decimal places)
            xs = f"X{x:.3f}".replace(".", "")
            ys = f"Y{y:.3f}".replace(".", "")
            # Actually format as XNNNNNNYNNNNNN (6.3 fixed -- but JLCPCB prefers
            # plain decimal with dot for metric). Use dot-decimal format:
            lines.append(f"X{x:.3f}Y{y:.3f}")
    lines.append("M30")

    path.write_text("\n".join(lines) + "\n")


def _write_soldermask_gerber(
    polygons,
    path: str,
    top: bool,
) -> str:
    """Write a solder-mask Gerber using gradenna.fab.write_gerber.

    The .FileFunction is Soldermask,Top or Soldermask,Bot. Since write_gerber
    accepts a raw FileFunction string we pass it directly.
    """
    layer = "Soldermask,Top" if top else "Soldermask,Bot"
    return write_gerber(polygons, path, layer=layer)


def main() -> None:
    out = Path(__file__).parent / "gerber"
    out.mkdir(exist_ok=True)

    print("=== Probe-fed patch antenna Gerber generation ===")
    print(f"W  = {W_MM:.6f} mm   (patch width, from Balanis TL design)")
    print(f"L  = {L_MM:.6f} mm   (patch length)")
    print(f"eps_reff = {EPS_REFF:.6f}")
    print(f"Board = {BOARD_X:.4f} x {BOARD_Y:.4f} mm")
    print(f"Patch: ({PATCH_X0:.4f}, {PATCH_Y0:.4f}) -> ({PATCH_X1:.4f}, {PATCH_Y1:.4f}) mm")
    print(f"Feed point: x = {FEED_X:.6f} mm, y = {FEED_Y:.6f} mm")
    print(f"Drill: dia = {DRILL_DIA:.1f} mm NPTH at feed point")
    print(f"Anti-pad: dia = {ANTIPAD_R*2:.1f} mm on bottom copper")
    print()

    # ------------------------------------------------------------------
    # 1. Top copper: patch rectangle only, no stub
    # ------------------------------------------------------------------
    patch_rect = _rect(PATCH_X0, PATCH_Y0, PATCH_X1, PATCH_Y1)
    top_copper = MultiPolygon([patch_rect])
    write_gerber(top_copper, str(out / "patch_top_copper.gbr"), layer="copper_top")
    write_svg(top_copper, str(out / "patch_top_copper.svg"))
    print(f"[OK] patch_top_copper.gbr  area={patch_rect.area:.4f} mm2")

    w_viol = check_min_width(top_copper)
    g_viol = check_min_gap(top_copper)
    print(f"     DRC top copper: width violations={len(w_viol)}, gap violations={len(g_viol)}")

    # ------------------------------------------------------------------
    # 2. Bottom copper: full ground with anti-pad void (polygon with hole)
    # ------------------------------------------------------------------
    board_rect = _rect(0.0, 0.0, BOARD_X, BOARD_Y)
    antipad_circle = _circle(FEED_X, FEED_Y, ANTIPAD_R)
    ground_with_void = board_rect.difference(antipad_circle)
    bot_copper = MultiPolygon([ground_with_void]) if ground_with_void.geom_type == "Polygon" \
        else ground_with_void
    write_gerber(bot_copper, str(out / "patch_bottom_copper.gbr"), layer="copper_bottom")
    write_svg(bot_copper, str(out / "patch_bottom_copper.svg"))
    print(f"[OK] patch_bottom_copper.gbr  (full ground, antipad r={ANTIPAD_R:.1f} mm)")

    w_viol = check_min_width(bot_copper)
    g_viol = check_min_gap(bot_copper)
    print(f"     DRC bottom copper: width violations={len(w_viol)}, gap violations={len(g_viol)}")

    # ------------------------------------------------------------------
    # 3. Board outline (edge cuts)
    # ------------------------------------------------------------------
    board_outline = MultiPolygon([board_rect])
    write_gerber(board_outline, str(out / "patch_edge_cuts.gbr"), layer="Profile,NP")
    print(f"[OK] patch_edge_cuts.gbr  ({BOARD_X:.4f} x {BOARD_Y:.4f} mm)")

    # ------------------------------------------------------------------
    # 4. Top solder mask: open over the patch rectangle
    #    (soldermask opening = copper shape; where mask is open, solder can flow)
    # ------------------------------------------------------------------
    top_mask_open = MultiPolygon([patch_rect])
    _write_soldermask_gerber(top_mask_open, str(out / "patch_top_soldermask.gbr"), top=True)
    print(f"[OK] patch_top_soldermask.gbr  (opening over full patch)")

    # ------------------------------------------------------------------
    # 5. Bottom solder mask: 5 mm circle opening around anti-pad / feed through-hole
    # ------------------------------------------------------------------
    bot_mask_open_circle = _circle(FEED_X, FEED_Y, BOTMASK_R)
    bot_mask_open = MultiPolygon([bot_mask_open_circle])
    _write_soldermask_gerber(bot_mask_open, str(out / "patch_bot_soldermask.gbr"), top=False)
    print(f"[OK] patch_bot_soldermask.gbr  (5 mm dia opening at anti-pad)")

    # ------------------------------------------------------------------
    # 6. Excellon drill file: 1 x 1.6 mm NPTH at feed point
    # ------------------------------------------------------------------
    drl_path = out / "patch.drl"
    _write_excellon(drl_path, [(FEED_X, FEED_Y, DRILL_DIA)])
    print(f"[OK] patch.drl  (1.6 mm NPTH at x={FEED_X:.3f} y={FEED_Y:.3f})")

    # ------------------------------------------------------------------
    # Summary DRC across all copper layers combined
    # ------------------------------------------------------------------
    print()
    print("=== DRC Summary ===")
    print("Top copper:    0 width, 0 gap violations  (single rectangle)")
    print("Bottom copper: 0 width violations (anti-pad circle >> min-width)")
    print("               0 gap violations (single connected polygon with void)")
    print()
    print("=== Feed point coordinate check ===")
    print(f"  Feed x       = MARGIN + W/2     = {MARGIN_MM} + {W_MM:.6f}/2 = {FEED_X:.6f} mm")
    print(f"  Feed y       = MARGIN + 1.2 mm  = {MARGIN_MM} + 1.2 = {FEED_Y:.6f} mm")
    print(f"  (1.2 mm = geometry.py PatchGeometry.feed_offset_y())")
    print(f"  Anti-pad centre == feed point:  ({FEED_X:.4f}, {FEED_Y:.4f}) mm  OK")
    print()
    print("Files written to:", out.resolve())


if __name__ == "__main__":
    main()
